"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const SalesController_1 = require("../../controllers/SalesController/SalesController");
const verifyUser_1 = require("../../utils/verifyUser");
const router = express_1.default.Router();
router.get('/available-prod', verifyUser_1.verifySales, SalesController_1.getAvailableProduction);
router.get('/prod/profile', verifyUser_1.verifySales, SalesController_1.viewIndividualprofile);
router.post('/createOrder', verifyUser_1.verifySales, SalesController_1.createOrder);
router.get('/orders', verifyUser_1.verifySales, SalesController_1.fetchOrder);
router.patch('/edit-req', verifyUser_1.verifySales, SalesController_1.editOrderRequest);
router.patch('/edit-order', verifyUser_1.verifySales, SalesController_1.editOrder);
router.delete('/deleteOrder', verifyUser_1.verifySales, SalesController_1.deleteOrder);
router.post('/prod-profile', verifyUser_1.verifySales, SalesController_1.productionProfile);
router.get('/checkSubscription', verifyUser_1.verifySales, SalesController_1.checkSubscription);
router.get('/report', verifyUser_1.verifySales, SalesController_1.getReport);
exports.default = router;
