"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const verifyUser_1 = require("../../utils/verifyUser");
const ProductionController_1 = require("../../controllers/ProductionController/ProductionController");
const fetchOrder_1 = require("../../controllers/ProductionController/fetchOrder");
const superAdmin_1 = require("../../controllers/SuperAdmin/superAdmin");
const router = express_1.default.Router();
router.get('/profile', verifyUser_1.verifyProduction, ProductionController_1.getProfile);
router.post('/addItem', verifyUser_1.verifyProduction, ProductionController_1.addItem);
router.get('/requests', verifyUser_1.verifyProduction, ProductionController_1.fetchRequestedRetailers);
router.delete('/delete-req', verifyUser_1.verifyProduction, ProductionController_1.rejectReq);
router.post('/acc-req', verifyUser_1.verifyProduction, ProductionController_1.acceptReq);
router.get('/orders', verifyUser_1.verifyProduction, fetchOrder_1.fetchOrdersAll);
router.get('/order-count', verifyUser_1.verifyProduction, fetchOrder_1.countOrder);
router.patch('/order-acc', verifyUser_1.verifyProduction, fetchOrder_1.acceptOrder);
router.patch('/order-rej', verifyUser_1.verifyProduction, fetchOrder_1.rejectOrder);
router.get('/available-sales', verifyUser_1.verifyProduction, ProductionController_1.availableSales);
router.post('/sales-prof', verifyUser_1.verifyProduction, ProductionController_1.getSalesProfile);
router.get('/conn-ret', verifyUser_1.verifyProduction, ProductionController_1.getConnRetailersList);
router.get('/avail-ret', verifyUser_1.verifyProduction, ProductionController_1.getAvailRetailList);
router.get('/ret-profile', verifyUser_1.verifyProduction, ProductionController_1.getRetailerProfile);
router.patch('/conn-req', verifyUser_1.verifyProduction, ProductionController_1.sendConnectionRequest);
router.patch('/subscription', verifyUser_1.verifyProduction, ProductionController_1.addSubscription);
router.get('/search-user', verifyUser_1.verifyProduction, ProductionController_1.searchRetailer);
router.get('/retailer-sort', verifyUser_1.verifyProduction, ProductionController_1.sortRetailer);
router.get('/report', verifyUser_1.verifyProduction, ProductionController_1.getReports);
router.get('/fetch-plans', verifyUser_1.verifyProduction, superAdmin_1.fetchPlans);
router.patch('/edit-acc', verifyUser_1.verifyProduction, ProductionController_1.acceptEditReq);
router.patch('/edit-deny', verifyUser_1.verifyProduction, ProductionController_1.denyEditRequest);
exports.default = router;
